export const FETCH_CHARITIES = 'FETCH_CHARITIES';
export const FETCH_PAYMENTS = 'FETCH_PAYMENTS';
export const UPDATE_TOTAL_DONATE = 'UPDATE_TOTAL_DONATE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';